// <auto-generated />
using Dx7Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Dx7Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324000003_AddChairAuditTenantId")]
    partial class AddChairAuditTenantId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Schema unchanged from EnableRls — this migration adds a column and RLS only.
            // Refer to 20260323000001_AddCdmSchema.Designer.cs for the full model definition.
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
