// <auto-generated />
using System;
using Dx7Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dx7Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324000001_EnableRls")]
    partial class EnableRls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Schema unchanged from AddCdmSchema — RLS policies are not reflected in the EF model.
            // Refer to 20260323000001_AddCdmSchema.Designer.cs for the full model definition.
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
